export const INSTRUCTORS = [
  {
    id: 1,
    name: "John Smith",
    field: "Computer Science",
    noOfStudents: 500,
    rating: 4.8,
    bio: "John Smith is an experienced computer scientist with expertise in programming languages such as Java, Python, and JavaScript. He has been teaching programming for over 10 years and has helped hundreds of students become proficient developers.",
    photo: "john_smith.jpg",
    contact: {
      email: "john@example.com",
      phone: "+1234567890",
      website: "http://www.johnsmith.com",
    },
  },
  {
    id: 2,
    name: "Alice Johnson",
    field: "Mathematics",
    noOfStudents: 300,
    rating: 4.9,
    bio: "Alice Johnson is a passionate mathematician with expertise in calculus, algebra, and geometry. She enjoys teaching complex mathematical concepts in a simplified manner and has a proven track record of helping students succeed in their math studies.",
    photo: "alice_johnson.jpg",
    contact: {
      email: "alice@example.com",
      phone: "+1234567890",
      website: "http://www.alicejohnson.com",
    },
  },
  {
    id: 3,
    name: "Michael Wang",
    field: "Physics",
    noOfStudents: 250,
    rating: 4.7,
    bio: "Michael Wang is a dedicated physicist specializing in quantum mechanics and relativity. He has a passion for teaching and enjoys making complex physics concepts accessible to students of all levels.",
    photo: "michael_wang.jpg",
    contact: {
      email: "michael@example.com",
      phone: "+1234567890",
      website: "http://www.michaelwang.com",
    },
  },
  {
    id: 4,
    name: "Emily Rodriguez",
    field: "Biology",
    noOfStudents: 400,
    rating: 4.6,
    bio: "Emily Rodriguez is a biologist with expertise in molecular biology and genetics. She has a passion for sharing her knowledge and inspiring students to explore the wonders of the natural world.",
    photo: "emily_rodriguez.jpg",
    contact: {
      email: "emily@example.com",
      phone: "+1234567890",
      website: "http://www.emilyrodriguez.com",
    },
  },
  {
    id: 5,
    name: "David Lee",
    field: "Chemistry",
    noOfStudents: 350,
    rating: 4.8,
    bio: "David Lee is a chemist specializing in organic chemistry and chemical synthesis. He enjoys engaging students in hands-on experiments and demonstrations to deepen their understanding of chemical concepts.",
    photo: "david_lee.jpg",
    contact: {
      email: "david@example.com",
      phone: "+1234567890",
      website: "http://www.davidlee.com",
    },
  },
  {
    id: 6,
    name: "Sophia Patel",
    field: "English Literature",
    noOfStudents: 200,
    rating: 4.9,
    bio: "Sophia Patel is an English literature professor with a passion for classic literature and poetry. She believes in fostering a love of reading and critical thinking skills in her students.",
    photo: "sophia_patel.jpg",
    contact: {
      email: "sophia@example.com",
      phone: "+1234567890",
      website: "http://www.sophiapatel.com",
    },
  },
  {
    id: 7,
    name: "Daniel Garcia",
    field: "History",
    noOfStudents: 300,
    rating: 4.7,
    bio: "Daniel Garcia is a historian specializing in ancient civilizations and world history. He enjoys bringing history to life through engaging storytelling and interactive lessons.",
    photo: "daniel_garcia.jpg",
    contact: {
      email: "daniel@example.com",
      phone: "+1234567890",
      website: "http://www.danielgarcia.com",
    },
  },
  {
    id: 8,
    name: "Jessica Kim",
    field: "Art",
    noOfStudents: 150,
    rating: 4.8,
    bio: "Jessica Kim is an artist and art educator passionate about fostering creativity and self-expression in her students. She enjoys exploring various art mediums and techniques with her students.",
    photo: "jessica_kim.jpg",
    contact: {
      email: "jessica@example.com",
      phone: "+1234567890",
      website: "http://www.jessicakim.com",
    },
  },
  {
    id: 10,
    name: "Kevin Nguyen",
    field: "Music",
    noOfStudents: 1230,
    rating: 5.0,
    bio: "Jessica Kim is an artist and art educator passionate about fostering creativity and self-expression in her students. She enjoys exploring various art mediums and techniques with her students.",
    photo: "jessica_kim.jpg",
    contact: {
      email: "jessica@example.com",
      phone: "+1234567890",
      website: "http://www.jessicakim.com",
    },
  },
  {
    id: 9,
    name: "Kevin Nguyen",
    field: "Music",
    noOfStudents: 1230,
    rating: 5.0,
    bio: "Jessica Kim is an artist and art educator passionate about fostering creativity and self-expression in her students. She enjoys exploring various art mediums and techniques with her students.",
    photo: "jessica_kim.jpg",
    contact: {
      email: "jessica@example.com",
      phone: "+1234567890",
      website: "http://www.jessicakim.com",
    },
  },
];
